let shopData= [
  {
    id: 1,
    name: "Smartphone",
    price: 20999.99,
    desc: "Powerful laptop with a quad-core i5 processor, 8GB RAM, 256GB SSD, and a 14-inch FHD display.",
    img: "images/mobiles.png",
  },
  {
    id: 2,
    name: "Laptoop",
    price: 9499.99,
    desc: "smartphone with a 6.2-inch screen, 12MP dual camera, 128GB storage, and a 4000mAh battery.",
    img: "images/laptop.png",
  },
  {
    id: 3,
    name: "Headphones",
    price: 5149.99,
    desc: "High-quality wireless headphones with over-ear design, 20 hours of battery life, and a sleek black color.",
    img: "images/headphone1.png",
  },
  {
    id: 4,
    name: "Watches",
    price: 5199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/watch.png",
  },
  {
    id: 5,
    name: "Speakers",
    price: 4149.99,
    desc: "High-quality wireless headphones with over-ear design, 20 hours of battery life, and a sleek black color.",
    img: "images/speakers.png",
  },
  {
    id: 6,
    name: "Television",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/tv.png",
  },
  {
    id: 7,
    name: "Stylish Headphone",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/headphone2.png",
  },
  {
    id: 8,
    name: "Iphone 12 Pro Max",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/iphone.png",
  },
];
