export let  shopItemsData = [
  {
    id: 1,
    name: "Ladies Bag",
    desc: "Awesome Ladies bag with a arogant color",
    img: "images/bag1.jpg",
    price: 24850,
    cat: "Bag",
  },
  {
    id: 2,
    name: "Leather Bag",
    desc: "Awesome Ladies bag with a arogant color",
    img: "images/bag2.jpg",
    price: 32900,
    cat: "Bag",
  },
  {
    id: 3,
    name: "Beautiful Bag",
    desc: "Awesome Ladies bag with a arogant color",
    img: "images/bag3.jpg",
    price: 32220,
    cat: "Bag",
  },
  {
    id: 4,
    name: "Stylish Bag",
    desc: "Awesome Ladies bag with a arogant color",
    img: "images/bag4.jpg",
    price: 11920,
    cat: "Bag",
  },
  {
    id: 5,
    name: "Smartphone",
    price: 20999.99,
    desc: "Powerful laptop with a quad-core i5 processor, 8GB RAM, 256GB SSD, and a 14-inch FHD display.",
    img: "images/mobiles.png",
    cat: "Electronics",
  },
  {
    id: 6,
    name: "Laptop",
    price: 9499.99,
    desc: "smartphone with a 6.2-inch screen, 12MP dual camera, 128GB storage, and a 4000mAh battery.",
    img: "images/laptop.png",
    cat: "Electronics",
  },
  {
    id: 37,
    name: "Laptop",
    price: 9499.99,
    desc: "smartphone with a 6.2-inch screen, 12MP dual camera, 128GB storage, and a 4000mAh battery.",
    img: "images/lapi.png",
    cat: "Electronics",
  },
  {
    id: 7,
    name: "Headphones",
    price: 5149.99,
    desc: "High-quality wireless headphones with over-ear design, 20 hours of battery life, and a sleek black color.",
    img: "images/headphone1.png",
    cat: "Electronics",
  },
  {
    id: 8,
    name: "Watches",
    price: 5199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/watch.png",
    cat: "Electronics",
  },
  {
    id: 9,
    name: "Speakers",
    price: 4149.99,
    desc: "High-quality wireless headphones with over-ear design, 20 hours of battery life, and a sleek black color.",
    img: "images/speakers.png",
    cat: "Electronics",
  },
  {
    id: 10,
    name: "Television",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/tv.png",
    cat: "Electronics",
  },
  {
    id: 11,
    name: "Stylish Headphone",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/headphone2.png",
    cat: "Electronics",
  },
  {
    id: 12,
    name: "Iphone 12 Pro Max",
    price: 19199.99,
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/iphone.png",
    cat: "Electronics",
  },
  {
    id: 13,
    name: "Stylish Rolex Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/watch1.jpg",
    price: 99100,
    cat: "Watch",
  },
  {
    id: 14,
    name: "Stylish Rolex Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant, fitness tracking features, and a stylish silver color.",
    img: "images/watch2.jpg",
    price: 90250,
    cat: "Watch",
  },
  {
    id: 15,
    name: "Stylish Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch3.jpg",
    price: 8300,
    cat: "Watch",
  },
  {
    id: 16,
    name: "Liked watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch4.jpg",
    price: 9350,
    cat: "Watch",
  },
  {
    id: 17,
    name: "Simple Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch5.jpg",
    price: 99400,
    cat: "Watch",
  },
  {
    id: 18,
    name: "Watch item",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch6.jpg",
    price: 7400,
    cat: "Watch",
  },
  {
    id: 19,
    name: "Watch item",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch7.jpg",
    price: 99400,
    cat: "Watch",
  },
  {
    id: 20,
    name: "Watch item",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch8.jpg",
    price: 98400,
    cat: "Watch",
  },
  {
    id: 21,
    name: "Good Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch9.jpg",
    price: 88400,
    cat: "Watch",
  },
  {
    id: 22,
    name: "Good Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch10.jpg",
    price: 99400,
    cat: "Watch",
  },
  {
    id: 23,
    name: "Good Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch11.jpg",
    price: 9400,
    cat: "Watch",
  },
  {
    id: 24,
    name: "Good Watch",
    desc: "Smartwatch with a 1.3-inch display, water-resistant",
    img: "images/watch12.jpg",
    price: 9000,
    cat: "Watch",
  },
  {
    id: 25,
    name: "Liked Jeans",
    desc: "Regular jeans with a slim fit and a dark wash.",
    img: "images/jeans1.jpg",
    price: 4950,
    cat: "Jeans",
  },
  {
    id: 26,
    name: "Liked Jeans",
    desc: "Regular jeans with a slim fit and a dark wash.",
    img: "images/jeans2.jpg",
    price: 9950,
    cat: "Jeans",
  },
  {
    id: 27,
    name: "Liked Jeans",
    desc: "Regular jeans with a slim fit and a dark wash.",
    img: "images/jeans3.jpg",
    price: 9500,
    cat: "Jeans",
  },
  {
    id: 28,
    name: "Liked Jeans",
    desc: "Regular jeans with a slim fit and a dark wash.",
    img: "images/jeans4.jpg",
    price: 4505,
    cat: "Jeans",
  },
  {
    id: 29,
    name: "Pure Leather Jacket",
    desc: "Regular Jacket with a slim fit and a dark wash.",
    img: "images/jacket1.jpg",
    price: 5550,
    cat: "Jacket",
  },
  {
    id: 30,
    name: "Pure Leather Jacket",
    desc: "Regular Jacket with a slim fit and a dark wash.",
    img: "images/jacket2.jpg",
    price: 5000,
    cat: "Jacket",
  },
  {
    id: 31,
    name: "Unique watch item",
    desc: "Regular Jacket with a slim fit and a dark wash.",
    img: "images/jacket3.jpg",
    price: 55000,
    cat: "Jacket",
  },
  {
    id: 32,
    name: "Summer Sunglasses",
    desc: "Regular Jacket with a slim fit and a dark wash.",
    img: "images/jacket4.jpg",
    price: 6000,
    cat: "Jacket",
  },
  {
    id: 33,
    name: "Summer Sunglasses",
    desc: "Awesome Sunglasses with a beautiful view",
    img: "images/sunglass1.jpg",
    price: 6500,
    cat: "Sunglass",
  },
  {
    id: 34,
    name: "Stylish Sun Glass",
    desc: "Awesome Sunglasses with a beautiful view",
    img: "images/sunglass2.jpg",
    price: 7005,
    cat: "Sunglass",
  },
  {
    id: 35,
    name: "Sun Glass",
    desc: "Awesome Sunglasses with a beautiful view",
    img: "images/sunglass3.jpg",
    price: 7560,
    cat: "Sunglass",
  },
  {
    id: 36,
    name: "Stylish Sun Glass",
    desc: "Awesome Sunglasses with a beautiful view",
    img: "images/sunglass4.jpg",
    price: 8400,
    cat: "Sunglass",
  },
];
